// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Smart_Yard_Manager.Infrastructure.Context;

#nullable disable

namespace Smart_Yard_Manager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smart_Yard_Manager.Domain.Entity.Moviment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<string>("PlacaMoto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PLACA_MOTO");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("SENSOR_ID");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("MOVIMENTS", (string)null);
                });

            modelBuilder.Entity("Smart_Yard_Manager.Domain.Entity.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<int>("Section")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SECTION");

                    b.HasKey("Id");

                    b.ToTable("SENSORS", (string)null);
                });

            modelBuilder.Entity("Smart_Yard_Manager.Domain.Entity.Moviment", b =>
                {
                    b.HasOne("Smart_Yard_Manager.Domain.Entity.Sensor", "Sensor")
                        .WithMany("Moviments")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Smart_Yard_Manager.Domain.Entity.Sensor", b =>
                {
                    b.Navigation("Moviments");
                });
#pragma warning restore 612, 618
        }
    }
}
